# BASH completion script for pymctp
# Generated by pycomplete 0.4.0

_pymctp_3965eda095e44947_complete()
{
    local cur script coms opts com
    COMPREPLY=()
    _get_comp_words_by_ref -n : cur words

    # for an alias, get the real script behind it
    if [[ $(type -t ${words[0]}) == "alias" ]]; then
        script=$(alias ${words[0]} | sed -E "s/alias ${words[0]}='(.*)'/\\1/")
    else
        script=${words[0]}
    fi

    # lookup for command
    for word in ${words[@]:1}; do
        if [[ $word != -* ]]; then
            com=$word
            break
        fi
    done

    # completing for an option
    if [[ ${cur} == --* ]] ; then
        opts="--help --version"

        case "$com" in

            (analyze-tcpdump)
            opts="--date --dst --gap-threshold --help --json-report --min-severity --no-dst --no-triage --packet-log --response-timeout --rules --timezone --triage"
            ;;

            (completions)
            opts="--dynamic --help"
            ;;

            (extensions)
            opts="--help"
            ;;

        esac

        COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
        __ltrim_colon_completions "$cur"

        return 0;
    fi

    # completing for a command
    if [[ $cur == $com ]]; then
        coms="analyze-tcpdump completions extensions"

        COMPREPLY=($(compgen -W "${coms}" -- ${cur}))
        __ltrim_colon_completions "$cur"

        return 0
    fi
}

complete -o default -F _pymctp_3965eda095e44947_complete pymctp

