#compdef pymctp

# ZSH completion script for pymctp
# Generated by pycomplete 0.4.0

_pymctp_3965eda095e44947_complete()
{
    local state com cur opts

    cur=${words[${#words[@]}]}

    # lookup for command
    for word in ${words[@]:1}; do
        if [[ $word != -* ]]; then
            com=$word
            break
        fi
    done

    if [[ ${cur} == --* ]]; then
        state="option"
        opts=("--help:Show this message and exit." "--version:Show the version and exit.")
    elif [[ $cur == $com ]]; then
        state="command"
        coms=("analyze-tcpdump" "completions" "extensions")
    fi

    case $state in
        (command)
            _describe 'command' coms
        ;;
        (option)
            case "$com" in

            (analyze-tcpdump)
            ;;

            (completions)
            opts=("--dynamic:Regenerate completions dynamically \(includes plugin commands, requires pycomplete\)." "--help:Show this message and exit.")
            ;;

            (extensions)
            opts=("--help:Show this message and exit.")
            ;;

            esac

            _describe 'option' opts
        ;;
        *)
            # fallback to file completion
            _arguments '*:file:_files'
    esac
}

_pymctp_3965eda095e44947_complete "$@"


