# Re-export all open-source Cerberus types and packets from upstream
from pymctp.layers.mctp.vdpci.cerberus import (  # noqa: F401
    CerberusCmdCodes,
    CerberusErrorCodes,
    CerberusLogType,
    CerberusResetConfig,
    CerberusUpdateType,
    ComponentAttestStatus,
    ErrorResponsePacket,
    FwVersionCmdPacket,
    FwVersionRequestPacket,
    FwVersionResponsePacket,
    DeviceCapsCmdPacket,
    DeviceCapsRequestPacket,
    DeviceCapsResponsePacket,
    DeviceIdCmdPacket,
    DeviceIdResponsePacket,
    GetDeviceIdRequestPacket,
    DeviceInfoCmdPacket,
    DeviceInfoResponsePacket,
    GetDeviceInfoRequestPacket,
    ExportCsrCmdPacket,
    ExportCsrRequestPacket,
    ExportCsrResponsePacket,
    ImportCertRequestPacket,
    SignedCertStateCmdPacket,
    GetSignedCertStateRequestPacket,
    SignedCertStateResponsePacket,
    HostStateCmdPacket,
    GetHostStateRequestPacket,
    HostStateResponsePacket,
    LogInfoCmdPacket,
    GetLogInfoRequestPacket,
    LogInfoResponsePacket,
    ReadLogCmdPacket,
    ReadLogRequestPacket,
    ReadLogResponsePacket,
    ClearLogRequestPacket,
    AttestationDataCmdPacket,
    GetAttestationDataRequestPacket,
    AttestationDataResponsePacket,
    ManifestIdCmdPacket,
    GetManifestIdRequestPacket,
    ManifestIdResponsePacket,
    PfmSupportedFwCmdPacket,
    GetPfmSupportedFwRequestPacket,
    PfmSupportedFwResponsePacket,
    InitManifestUpdateRequestPacket,
    ManifestUpdateRequestPacket,
    CompleteManifestUpdateRequestPacket,
    ComponentIdsCmdPacket,
    GetComponentIdsRequestPacket,
    ComponentIdsResponsePacket,
    InitFwUpdateRequestPacket,
    FwUpdateRequestPacket,
    CompleteFwUpdateRequestPacket,
    UpdateStatusCmdPacket,
    GetUpdateStatusRequestPacket,
    UpdateStatusResponsePacket,
    ExtUpdateStatusCmdPacket,
    GetExtUpdateStatusRequestPacket,
    ExtUpdateStatusResponsePacket,
    ResetConfigRequestPacket,
    ConfigIdCmdPacket,
    GetConfigIdRequestPacket,
    ConfigIdResponsePacket,
    TriggerFwRecoveryRequestPacket,
    PrepareRecoveryImageRequestPacket,
    UpdateRecoveryImageRequestPacket,
    ActivateRecoveryImageRequestPacket,
    RecoveryImageVersionCmdPacket,
    GetRecoveryImageVersionRequestPacket,
    RecoveryImageVersionResponsePacket,
    PmrCmdPacket,
    GetPmrRequestPacket,
    PmrResponsePacket,
    DigestCmdPacket,
    GetDigestRequestPacket,
    DigestResponsePacket,
    CertificateCmdPacket,
    GetCertificateRequestPacket,
    CertificateResponsePacket,
    AttestationChallengeCmdPacket,
    AttestationChallengeRequestPacket,
    AttestationChallengeResponsePacket,
    ExchangeKeysCmdPacket,
    ExchangeKeysRequestPacket,
    ExchangeKeysResponsePacket,
    SessionSyncCmdPacket,
    SessionSyncRequestPacket,
    SessionSyncResponsePacket,
    UpdatePmrCmdPacket,
    UpdatePmrRequestPacket,
    UpdatePmrResponsePacket,
    ResetCounterCmdPacket,
    ResetCounterRequestPacket,
    ResetCounterResponsePacket,
    UnsealMessageRequestPacket,
    UnsealMessageResultCmdPacket,
    UnsealMessageResultRequestPacket,
    UnsealMessageResultResponsePacket,
)

# Private types
from .types import (  # noqa: F401
    ChallengeCmdCodes,
    DiagCmdCodes,
    OverlakeCmdCodes,
    PrivateCerberusCmdCodes,
)

# Private Overlake-specific packets (also registers bind_layers)
from .overlake import (  # noqa: F401
    SocInitFwUpdateRequestPacket,
    SocUpdateFwRequestPacket,
)

# Private Microsoft Cerberus packets (also registers bind_layers)
from .msft_cerberus import (  # noqa: F401
    COMPONENT_MAP,
    ComponentInstanceEntry,
    ComponentInstanceInfoCmdPacket,
    ComponentInstanceInfoResponsePacket,
    ForceAttestationCmdPacket,
    ForceAttestationRequestPacket,
    ForceAttestationResponsePacket,
    GetComponentInstanceInfoRequestPacket,
)

# Register OEM component map for AttestData response decoding
AttestationDataResponsePacket.component_maps.append(COMPONENT_MAP)
