from enum import IntEnum

from pymctp.layers.mctp.vdpci.cerberus.types import (
    CerberusCmdCodes,
    CerberusErrorCodes,
    CerberusLogType,
    CerberusResetConfig,
    CerberusUpdateType,
)


class OverlakeCmdCodes(IntEnum):
    """Microsoft Overlake-specific command codes."""

    GET_STORAGE = 0xA1
    SET_STORAGE = 0xA2
    GET_COUNTER = 0xA3
    INCREMENT_COUNTER = 0xA4
    READ_DATA = 0xA5
    CLEAR_DATA = 0xA6
    STORE_DATA = 0xA7
    SIGN_DATA = 0xA8
    GET_FPGA_BOOT_MODE = 0xB0
    SET_FPGA_BOOT_MODE = 0xB1
    GET_SOC_FW_HEADER = 0xB3
    SOC_RESET = 0xE0
    SOC_INIT_FW_UPDATE = 0xE1
    SOC_UPDATE_FW = 0xE2
    TRIGGER_NMI = 0xE3
    GET_BOOT_DEVICE = 0xE4
    SET_BOOT_DEVICE = 0xE5
    GET_MAC_ADDRESS = 0xE6
    GET_DEBUG_LOG_INFO = 0xE7
    GET_DEBUG_LOG = 0xE8
    GET_SOC_UPDATE_STATUS = 0xE9
    TPM_CLEAR = 0xEA
    GET_PUBLIC_KEY = 0xEB
    DECRYPT_PAYLOAD = 0xEC
    SET_DEBUG_VERBOSITY = 0xED
    GET_DEBUG_VERBOSITY = 0xEE
    GET_SOC_FWVERSION = 0xEF


class PrivateCerberusCmdCodes(IntEnum):
    """Private Cerberus protocol command codes (not publicly published)."""

    GET_PCD_COMPONENT_INSTANCE_INFO = 0x8F
    FORCE_ATTESTATION = 0x90


class DiagCmdCodes(IntEnum):
    """Diagnostic and debug command codes (private)."""

    DIAG_HEAP_USAGE = 0xD0
    DEBUG_START_ATTESTATION = 0xF0
    DEBUG_GET_ATTESTATION_STATE = 0xF1
    DEBUG_FILL_LOG = 0xF2
    DEBUG_RESERVED = 0xFF


class ChallengeCmdCodes(IntEnum):
    """Combined command codes for backward compatibility.

    Includes all open-source Cerberus commands plus Overlake/diagnostic extensions.
    Prefer using CerberusCmdCodes or OverlakeCmdCodes directly.
    """

    # Open-source Cerberus commands
    CERBERUS_PROTOCOL_GET_FW_VERSION = CerberusCmdCodes.GET_FW_VERSION
    CERBERUS_PROTOCOL_GET_DEVICE_CAPABILITIES = CerberusCmdCodes.GET_DEVICE_CAPABILITIES
    CERBERUS_PROTOCOL_GET_DEVICE_ID = CerberusCmdCodes.GET_DEVICE_ID
    CERBERUS_PROTOCOL_GET_DEVICE_INFO = CerberusCmdCodes.GET_DEVICE_INFO
    CERBERUS_PROTOCOL_EXPORT_CSR = CerberusCmdCodes.EXPORT_CSR
    CERBERUS_PROTOCOL_IMPORT_CA_SIGNED_CERT = CerberusCmdCodes.IMPORT_CA_SIGNED_CERT
    CERBERUS_PROTOCOL_GET_SIGNED_CERT_STATE = CerberusCmdCodes.GET_SIGNED_CERT_STATE
    CERBERUS_PROTOCOL_GET_HOST_STATE = CerberusCmdCodes.GET_HOST_STATE
    CERBERUS_PROTOCOL_GET_LOG_INFO = CerberusCmdCodes.GET_LOG_INFO
    CERBERUS_PROTOCOL_READ_LOG = CerberusCmdCodes.READ_LOG
    CERBERUS_PROTOCOL_CLEAR_LOG = CerberusCmdCodes.CLEAR_LOG
    CERBERUS_PROTOCOL_GET_ATTESTATION_DATA = CerberusCmdCodes.GET_ATTESTATION_DATA
    CERBERUS_PROTOCOL_GET_PFM_ID = CerberusCmdCodes.GET_PFM_ID
    CERBERUS_PROTOCOL_GET_PFM_SUPPORTED_FW = CerberusCmdCodes.GET_PFM_SUPPORTED_FW
    CERBERUS_PROTOCOL_INIT_PFM_UPDATE = CerberusCmdCodes.INIT_PFM_UPDATE
    CERBERUS_PROTOCOL_PFM_UPDATE = CerberusCmdCodes.PFM_UPDATE
    CERBERUS_PROTOCOL_COMPLETE_PFM_UPDATE = CerberusCmdCodes.COMPLETE_PFM_UPDATE
    CERBERUS_PROTOCOL_GET_CFM_ID = CerberusCmdCodes.GET_CFM_ID
    CERBERUS_PROTOCOL_INIT_CFM_UPDATE = CerberusCmdCodes.INIT_CFM_UPDATE
    CERBERUS_PROTOCOL_CFM_UPDATE = CerberusCmdCodes.CFM_UPDATE
    CERBERUS_PROTOCOL_COMPLETE_CFM_UPDATE = CerberusCmdCodes.COMPLETE_CFM_UPDATE
    CERBERUS_PROTOCOL_GET_PCD_ID = CerberusCmdCodes.GET_PCD_ID
    CERBERUS_PROTOCOL_INIT_PCD_UPDATE = CerberusCmdCodes.INIT_PCD_UPDATE
    CERBERUS_PROTOCOL_PCD_UPDATE = CerberusCmdCodes.PCD_UPDATE
    CERBERUS_PROTOCOL_COMPLETE_PCD_UPDATE = CerberusCmdCodes.COMPLETE_PCD_UPDATE
    CERBERUS_PROTOCOL_INIT_FW_UPDATE = CerberusCmdCodes.INIT_FW_UPDATE
    CERBERUS_PROTOCOL_FW_UPDATE = CerberusCmdCodes.FW_UPDATE
    CERBERUS_PROTOCOL_GET_UPDATE_STATUS = CerberusCmdCodes.GET_UPDATE_STATUS
    CERBERUS_PROTOCOL_COMPLETE_FW_UPDATE = CerberusCmdCodes.COMPLETE_FW_UPDATE
    CERBERUS_PROTOCOL_RESET_CONFIG = CerberusCmdCodes.RESET_CONFIG
    CERBERUS_PROTOCOL_GET_CONFIG_ID = CerberusCmdCodes.GET_CONFIG_ID
    CERBERUS_PROTOCOL_TRIGGER_FW_RECOVERY = CerberusCmdCodes.TRIGGER_FW_RECOVERY
    CERBERUS_PROTOCOL_PREPARE_RECOVERY_IMAGE = CerberusCmdCodes.PREPARE_RECOVERY_IMAGE
    CERBERUS_PROTOCOL_UPDATE_RECOVERY_IMAGE = CerberusCmdCodes.UPDATE_RECOVERY_IMAGE
    CERBERUS_PROTOCOL_ACTIVATE_RECOVERY_IMAGE = CerberusCmdCodes.ACTIVATE_RECOVERY_IMAGE
    CERBERUS_PROTOCOL_GET_RECOVERY_IMAGE_VERSION = CerberusCmdCodes.GET_RECOVERY_IMAGE_VERSION
    CERBERUS_PROTOCOL_ERROR = CerberusCmdCodes.ERROR
    CERBERUS_PROTOCOL_GET_PMR = CerberusCmdCodes.GET_PMR
    CERBERUS_PROTOCOL_GET_DIGEST = CerberusCmdCodes.GET_DIGEST
    CERBERUS_PROTOCOL_GET_CERTIFICATE = CerberusCmdCodes.GET_CERTIFICATE
    CERBERUS_PROTOCOL_ATTESTATION_CHALLENGE = CerberusCmdCodes.ATTESTATION_CHALLENGE
    CERBERUS_PROTOCOL_EXCHANGE_KEYS = CerberusCmdCodes.EXCHANGE_KEYS
    CERBERUS_PROTOCOL_SESSION_SYNC = CerberusCmdCodes.SESSION_SYNC
    CERBERUS_PROTOCOL_UPDATE_PMR = CerberusCmdCodes.UPDATE_PMR
    CERBERUS_PROTOCOL_RESET_COUNTER = CerberusCmdCodes.RESET_COUNTER
    CERBERUS_PROTOCOL_UNSEAL_MESSAGE = CerberusCmdCodes.UNSEAL_MESSAGE
    CERBERUS_PROTOCOL_UNSEAL_MESSAGE_RESULT = CerberusCmdCodes.UNSEAL_MESSAGE_RESULT
    CERBERUS_PROTOCOL_GET_CFM_SUPPORTED_COMPONENT_IDS = CerberusCmdCodes.GET_CFM_SUPPORTED_COMPONENT_IDS
    CERBERUS_PROTOCOL_GET_EXT_UPDATE_STATUS = CerberusCmdCodes.GET_EXT_UPDATE_STATUS
    CERBERUS_PROTOCOL_GET_PCD_COMPONENT_INSTANCE_INFO = PrivateCerberusCmdCodes.GET_PCD_COMPONENT_INSTANCE_INFO
    CERBERUS_PROTOCOL_FORCE_ATTESTATION = PrivateCerberusCmdCodes.FORCE_ATTESTATION

    # Overlake-specific
    OVERLAKE_PROTOCOL_GET_STORAGE = OverlakeCmdCodes.GET_STORAGE
    OVERLAKE_PROTOCOL_SET_STORAGE = OverlakeCmdCodes.SET_STORAGE
    OVERLAKE_PROTOCOL_GET_COUNTER = OverlakeCmdCodes.GET_COUNTER
    OVERLAKE_PROTOCOL_INCREMENT_COUNTER = OverlakeCmdCodes.INCREMENT_COUNTER
    OVERLAKE_PROTOCOL_READ_DATA = OverlakeCmdCodes.READ_DATA
    OVERLAKE_PROTOCOL_CLEAR_DATA = OverlakeCmdCodes.CLEAR_DATA
    OVERLAKE_PROTOCOL_STORE_DATA = OverlakeCmdCodes.STORE_DATA
    OVERLAKE_PROTOCOL_SIGN_DATA = OverlakeCmdCodes.SIGN_DATA
    OVERLAKE_PROTOCOL_GET_FPGA_BOOT_MODE = OverlakeCmdCodes.GET_FPGA_BOOT_MODE
    OVERLAKE_PROTOCOL_SET_FPGA_BOOT_MODE = OverlakeCmdCodes.SET_FPGA_BOOT_MODE
    OVERLAKE_PROTOCOL_GET_SOC_FW_HEADER = OverlakeCmdCodes.GET_SOC_FW_HEADER
    OVERLAKE_PROTOCOL_SOC_RESET = OverlakeCmdCodes.SOC_RESET
    OVERLAKE_PROTOCOL_SOC_INIT_FW_UPDATE = OverlakeCmdCodes.SOC_INIT_FW_UPDATE
    OVERLAKE_PROTOCOL_SOC_UPDATE_FW = OverlakeCmdCodes.SOC_UPDATE_FW
    OVERLAKE_PROTOCOL_TRIGGER_NMI = OverlakeCmdCodes.TRIGGER_NMI
    OVERLAKE_PROTOCOL_GET_BOOT_DEVICE = OverlakeCmdCodes.GET_BOOT_DEVICE
    OVERLAKE_PROTOCOL_SET_BOOT_DEVICE = OverlakeCmdCodes.SET_BOOT_DEVICE
    OVERLAKE_PROTOCOL_GET_MAC_ADDRESS = OverlakeCmdCodes.GET_MAC_ADDRESS
    OVERLAKE_PROTOCOL_GET_DEBUG_LOG_INFO = OverlakeCmdCodes.GET_DEBUG_LOG_INFO
    OVERLAKE_PROTOCOL_GET_DEBUG_LOG = OverlakeCmdCodes.GET_DEBUG_LOG
    OVERLAKE_PROTOCOL_GET_SOC_UPDATE_STATUS = OverlakeCmdCodes.GET_SOC_UPDATE_STATUS
    OVERLAKE_PROTOCOL_TPM_CLEAR = OverlakeCmdCodes.TPM_CLEAR
    OVERLAKE_PROTOCOL_GET_PUBLIC_KEY = OverlakeCmdCodes.GET_PUBLIC_KEY
    OVERLAKE_PROTOCOL_DECRYPT_PAYLOAD = OverlakeCmdCodes.DECRYPT_PAYLOAD
    OVERLAKE_PROTOCOL_SET_DEBUG_VERBOSITY = OverlakeCmdCodes.SET_DEBUG_VERBOSITY
    OVERLAKE_PROTOCOL_GET_DEBUG_VERBOSITY = OverlakeCmdCodes.GET_DEBUG_VERBOSITY
    OVERLAKE_PROTOCOL_GET_SOC_FWVERSION = OverlakeCmdCodes.GET_SOC_FWVERSION

    # Diagnostic/debug
    CERBERUS_PROTOCOL_DIAG_HEAP_USAGE = DiagCmdCodes.DIAG_HEAP_USAGE
    CERBERUS_PROTOCOL_DEBUG_START_ATTESTATION = DiagCmdCodes.DEBUG_START_ATTESTATION
    CERBERUS_PROTOCOL_DEBUG_GET_ATTESTATION_STATE = DiagCmdCodes.DEBUG_GET_ATTESTATION_STATE
    CERBERUS_PROTOCOL_DEBUG_FILL_LOG = DiagCmdCodes.DEBUG_FILL_LOG
    CERBERUS_PROTOCOL_DEBUG_RESERVED = DiagCmdCodes.DEBUG_RESERVED
