from enum import IntEnum


class MsftVdmBaseCmdCodes(IntEnum):
    STATUS = 0
    CMD_SET_SUPPORT = 1
    CAP_NEGOTIATION = 2
    GET_TEMP = 3
    HEARTBEAT_CTRL = 4
    HEARTBEAT = 5


class MsftVdmBmcCmdCodes(IntEnum):
    BMC_GET_SYSTEM_DEVICES = 0x13
    BMC_GET_DEVICE_STRING = 0x14
    BMC_GET_DEVICE_EID = 0x15


class MsftVdmRotCmdCodes(IntEnum):
    GET_ROT_CAPABILITIES = 0x00
    RESET_ROT = 0x01
    GET_TENANCY_GRANT_TOKEN = 0x02
    GET_UNLOCK_TOKEN = 0x03
    APPLY_UNLOCK_POLICY = 0x04
    CLEAR_UNLOCK_POLICY = 0x05
    GET_CRASH_DUMP_COUNT = 0x06
    GET_CRASH_DUMP_INFO = 0x07
    READ_CRASH_DUMP = 0x08
    CLEAR_CRASH_DUMP = 0x09
    GET_TIME = 0x0A
    SET_TIME = 0x0B
    GET_INTRUSION_DETECTION = 0x0C
    INTRUSION_EVENT = 0x0D
    GET_INTRUSION_COUNT = 0x0E
    WARM_RESET_EVENT_CONTROL = 0x0F
    PREPARE_FOR_WARM_RESET = 0x10
    WARM_RESET_COMPLETE = 0x11
